title: Settings
path: settings
icon: 'mdi:wrench'
badges: []
cards:
  - entities:
      - entity: input_select.home_mode
    show_header_toggle: false
    type: entities
  - entities:
      - entity: automation.turn_off_living_room_lights
    show_header_toggle: false
    title: Automations
    type: entities
