---
language: python
python:
  - "3.8"
before_install:
  - mv example-secrets.yaml secrets.yaml
  - mv example-service-account.json service-account.json
  - sudo apt-get install -y libudev-dev
  - git submodule update --init
install:
  - pip3 install homeassistant
  - pip3 install python-dateutil
  - pip3 install spotipy
  - pip3 install yamllint
script:
  - yamllint .
  - hass -c . --script check_config
