- alias: Turn on ZVOX when TV turns on
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_tv_status
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.zvox_power

- alias: "Unlock door from iOS"
  hide_entity: true
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: Unlock
  action:
    service: lock.unlock
    entity_id: lock.front_door

- alias: "Lock door from iOS"
  hide_entity: true
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: Lock
  action:
    service: lock.lock
    entity_id: lock.front_door

- alias: "Turn on lights before sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:15:00"
  action:
    - service: light.turn_on
      entity_id: light.corner_lamp
    - service: light.turn_on
      entity_id: light.tv_rack_lamp
    - service: light.turn_on
      entity_id: light.christmas_tree

- alias: "Turn off Christmas Tree"
  trigger:
    platform: time
    at: "02:00:00"
  action:
    - service: light.turn_off
      entity_id: light.christmas_tree

- alias: "Turn off Living Room lights"
  trigger:
    platform: time
    at: "22:30:00"
  action:
    - service: light.turn_off
      entity_id: light.living_room

- alias: "Home is now in Party Mode"
  trigger:
    platform: state
    entity_id: input_select.home_mode
    to: "Party"
  action:
    - service: automation.turn_off
      entity_id: automation.turn_off_living_room_lights

- alias: "Home is no longer in Party Mode"
  trigger:
    platform: state
    entity_id: input_select.home_mode
    from: "Party"
  action:
    - service: automation.turn_on
      entity_id: automation.turn_off_living_room_lights
