- alias: Turn on ZVOX when TV turns on
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_tv_status
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.zvox_power

- alias: "Turn on TV when PlayStation 4 turns on"
  trigger:
    platform: state
    entity_id: media_player.playstation_4
    from: 'standby'
  action:
    service: switch.turn_on
    entity_id: switch.ir_living_room_tv


- alias: "Unlock door from iOS"
  hide_entity: true
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: Unlock
  action:
    service: lock.unlock
    entity_id: lock.front_door

- alias: "Lock door from iOS"
  hide_entity: true
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: Lock
  action:
    service: lock.lock
    entity_id: lock.front_door

- alias: "Turn on lights before sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:15:00"
  action:
    - service: light.turn_on
      entity_id: light.corner_lamp
    - service: light.turn_on
      entity_id: light.tv_rack_lamp
    - service: light.turn_on
      entity_id: light.christmas_tree

- alias: "Turn off Christmas Tree"
  trigger:
    platform: time
    at: "02:00:00"
  action:
    - service: light.turn_off
      entity_id: light.christmas_tree

- alias: "Turn off Corner Lamp"
  trigger:
    platform: time
    at: "22:30:00"
  action:
    - service: light.turn_off
      entity_id: light.corner_lamp
    - service: light.turn_off
      entity_id: light.tv_rack_lamp
