---
default_config:

http:
  server_host: 127.0.0.1
  base_url: https://home.thepromisedlan.club/
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

logger:
  default: info
  logs:
    miflora: debug
    btlewrap: debug
    bluepy: debug

influxdb:
  host: 127.0.0.1
  port: 8086
  database: home-assistant
  include:
    entities:
      - sensor.bonsai_battery
      - sensor.bonsai_conductivity
      - sensor.bonsai_light_intensity
      - sensor.bonsai_moisture
      - sensor.bonsai_temperature
      - sensor.entryway_thermostat_humidity
      - sensor.entryway_thermostat_target
      - sensor.entryway_thermostat_temperature
      - sensor.outside_humidity
      - sensor.outside_temperature
      - sensor.office_air_quality
      - sensor.office_breath_voc_equivalent
      - sensor.office_co2_equivalent
      - sensor.office_gas_resistance
      - sensor.office_humidity
      - sensor.office_pressure
      - sensor.office_temperature

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml

api:

ios:

device_tracker:

notify:
  - name: Facebook
    platform: facebook
    page_access_token: !secret fb_page_access_token

history:
  use_include_order: true
  include: !include history.yaml

logbook:
  include: !include history.yaml

recorder:
  exclude:
    entities:
      - binary_sensor.living_room_tv_status

tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: https://home.thepromisedlan.club
    service_name: google_say

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  broker: 127.0.0.1

wake_on_lan:

google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !include service-account.json
  report_state: true
  expose_by_default: false
  entity_config:
    # living room
    lock.front_door:
      expose: true
      room: "Living Room"
    light.rack_lamps:
      expose: true
      room: "Living Room"
      aliases:
        - "Lamp"
        - "Lamps"
        - "Rack Lamp"
        - "Rack Lamps"
    light.christmas_tree:
      expose: true
      room: "Living Room"
      aliases:
        - "Christmas Tree Lights"
        - "Christmas Tree"
        - "Tree"
    vacuum.xiaomi_vacuum_cleaner:
      expose: true
      name: "Alfred"
      aliases:
        - "Vacuum"
        - "Vacuum Cleaner"
      room: "Living Room"
    switch.zvox_power:
      expose: true
      name: "ZVOX"
      aliases:
        - "ZVOX"
        - "ZVOX Speaker"
        - "Soundbar"
      room: "Living Room"

    # bedroom
    light.left_nightstand:
      expose: true
      room: "Bedroom"
    light.right_nightstand:
      expose: true
      room: "Bedroom"
    light.left_bedroom_lamp:
      expose: true
      room: "Bedroom"
    light.right_bedroom_lamp:
      expose: true
      room: "Bedroom"
    scene.relax:
      expose: true
      room: "Bedroom"
    scene.night:
      expose: true
      room: "Bedroom"
      aliases:
        - "Night"
        - "Night Time"
        - "Night Light"
    scene.reading_light:
      expose: true
      room: "Bedroom"

    # office
    light.workbench:
      expose: true
      room: "Office"
    light.desk:
      expose: true
      room: "Office"
    switch.grissom:
      expose: true
      name: "Hackintosh"
      aliases:
        - "Hackintosh"
        - "Grissom"
      room: "Office"

    # guest room
    light.guest_room_nightstand:
      expose: true
      aliases:
        - "Guest Room Nightstand"
        - "Guest Nightstand"
      room: "Guest Room"
    light.soup:
      expose: true
      aliases:
        - "Guest Room Lamp"
        - "Guest Lamp"
      room: "Guest Room"

    # garage
    cover.garage:
      expose: true
      room: "Garage"
      aliases:
        - "Garage"
        - "Garage Door"

homekit:
  filter:
    include_domains:
      - climate
      - cover
      - light
      - lock
    exclude_entities:
      - light.entertainment_area_1

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

zwave:
  usb_path: /dev/zwave

tplink:
  discovery: false
  switch:
    - host: "iot-avocado"
    - host: "iot-bacon"
    - host: "iot-pizza"

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
      allow_bypass_login: true
      trusted_users:
        192.168.1.0/24:
          - 568f9a82c34e4bbcb3275bc6ee3e3a60
  customize:
    # hide tuya switches since we are using them as lights
    switch.002008635ccf7f50842c:
      hidden: true
    switch.012002845ccf7f596568:
      hidden: true
    light.soup:
      friendly_name: "Guest Room Lamp"

light:
  - platform: switch
    name: "Guest Room Nightstand"
    entity_id: switch.avocado
  - platform: switch
    name: "Rack Lamps"
    entity_id: switch.bacon
  - platform: switch
    name: "Christmas Tree"
    entity_id: switch.pizza
  - platform: group
    name: Living Room
    entities:
      - light.christmas_tree
      - light.rack_lamps
  - platform: group
    name: Guest Room
    entities:
      - light.guest_room_nightstand
      - light.soup
  - platform: decora_wifi
    username: !secret leviton_username
    password: !secret leviton_password

august:
  login_method: email
  username: !secret august_username
  password: !secret august_password

cover:
  platform: opengarage
  covers:
    garage:
      name: Garage
      host: iot-opengarage
      device_key: !secret opengarage_device_key

vacuum:
  - platform: xiaomi_miio
    host: "iot-rockrobo"
    token: !secret roborock_token

switch:
  - platform: template
    switches:
      living_room_tv:
        friendly_name: "Living Room TV"
        value_template: >-
          {{ not is_state('binary_sensor.living_room_tv_status', 'off') }}
        icon_template: "mdi:television"
        turn_on:
          service: switch.turn_on
          entity_id: switch.ir_living_room_tv
        turn_off:
          service: switch.turn_off
          entity_id: switch.ir_living_room_tv
      bedroom_tv:
        friendly_name: "Bedroom TV"
        value_template: "{{ not is_state('media_player.bedroom_tv', 'off') }}"
        icon_template: "mdi:television"
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.bedroom_tv
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.bedroom_tv
      grissom:
        friendly_name: "Grissom"
        value_template: >-
          {{ not is_state('binary_sensor.grissom_status', 'off') }}
        icon_template: "mdi:desktop-mac"
        turn_on:
          service: wake_on_lan.send_magic_packet
          data:
            mac: !secret grissom_mac
        turn_off:
          # TODO: find a way to sleep my hackintosh
          service: wake_on_lan.send_magic_packet
          data:
            mac: !secret grissom_mac
  - platform: broadlink
    mac: !secret broadlink_mac
    switches:
      - name: "ZVOX Volume Up"
        command_off: "JgBIAAABKJQTExITEhMSFBEUEhMSExIUEjcSFBM2EhQSNxI4EjgSNxIUE\
          jcSOBIUETgSFBEUEhMSOBITEhMSOBITEjgSOBI3EgANBQ=="
      - name: "ZVOX Volume Down"
        command_off: "JgBIAAABKJQTEhIUExISExIUExITEhMSEzcSExM3ExISOBQ2EzYTNxIUE\
          jcUEhITExMSEhMTEhMTNxITEzcSNxM3FDYTNhM3EgANBQ===="
      - name: "ZVOX Mute"
        command_off: "JgBQAAABJpMSExISExISExMRFBESExMRFDYTEhM3EhITNxM2EjcUNhM3E\
          hMSEhM3EzYSExMRFBETEhM3EjcTEhITEzYSNxQ2EwAFZgABJ0kSAA0FAAAAAAAAAAA="
      - name: "ZVOX Power"
        command_on: "JgBQAAABKJMSEhISEhISEhISEhISEhISEjcSEhI3EhISNxI3EjcSNxI3Ej\
          cSEhI3EhISNxI3EjcSEhISEjcSEhI3EhISEhISEgAFZAABKEoSAAxWDQUAAAAAAAA="
        command_off: "JgBQAAABKJMSEhISEhISEhISEhISEhISEjcSEhI3EhISNxI3EjcSNxI3E\
          jcSEhI3EjcSEhISEhISEhISEjcSEhISEjcSNxI3EgAFZAABKEoSAAxWDQUAAAAAAAA="
      - name: "IR Living Room TV"
        command_on: "JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTER\
          ISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU="
        command_off: "JgBYAAABKpIVEBUQFjQVEBYQFRAVEBYPFjQVNRUQFjQVNRQ1FTUVNRUQF\
          RAWEBU0FhAVEBUQFRAWNBU1FTQVERU0FTUWNBU1FQAFMgABK0cVAAxOAAErRxUADQU="
  - platform: flux
    start_time: "7:00"
    stop_time: "22:00"
    lights:
      - light.desk
      - light.workbench
    mode: mired
    disable_brightness_adjust: true

webostv:
  name: "webOS Living Room TV"
  host: "living-room-tv"
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret webostv_mac
  customize:
    sources:
      - Chromecast
      - PlayStation 5
      - Nintendo Switch

sensor: !include_dir_merge_list sensors/

binary_sensor:
  - platform: ping
    name: living_room_tv_status
    host: "living-room-tv"
    scan_interval: 2
    count: 1
  - platform: template
    sensors:
      grissom_status:
        value_template: >-
          {{ (states('sensor.grissom_seconds_since_last_update') | int) < 60 }}
      is_freezing:
        value_template: "{{ (states('sensor.outside_temperature') | int) < 0 }}"
  - platform: workday
    name: workday_today
    country: US
  - platform: workday
    name: workday_tomorrow
    country: US
    days_offset: 1

input_select:
  home_mode:
    name: "Home Mode"
    options:
      - "Home"
      - "Away"
      - "Party"
      - "Guests"
    initial: "Home"
    icon: mdi:home
  router_selected_interface:
    name: "Router Interface"
    options:
      - "WAN (eth1.2)"
      - "LAN (br-lan)"
      - "IoT (br-iot)"
    initial: "WAN (eth1.2)"
    icon: mdi:network-router
  router_selected_wifi:
    name: "Router Interface"
    options:
      - "The Promised LAN (5GHz)"
      - "The Promised LAN (2.4GHz)"
      - "IoT (2.4GHz)"
    initial: "The Promised LAN (5GHz)"
    icon: mdi:access-point-network

counter:
  num_vacuum_retries_today:
    initial: 0
    step: 1

spotcast:
  sp_dc: !secret spotify_sp_dc
  sp_key: !secret spotify_sp_key
