default_config:

http:
  server_host: 127.0.0.1
  base_url: https://home.thepromisedlan.club/
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

logger:
  default: info
  logs:
    miflora: debug
    btlewrap: debug
    bluepy: debug

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml

api:

ios:

history:
  use_include_order: true
  include: !include history.yaml

logbook:
  include: !include history.yaml

recorder:
  exclude:
    entities:
      - sensor.valetudo_map
      - binary_sensor.living_room_tv_status

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  broker: 127.0.0.1

wake_on_lan:

google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !include service-account.json
  report_state: true
  expose_by_default: false
  entity_config:
    light.desk_lamp:
      expose: true
      room: "Living Room"
    light.corner_lamp:
      expose: true
      room: "Living Room"
    light.tv_rack_lamp:
      expose: true
      room: "Living Room"
    vacuum.xiaomi_vacuum_cleaner:
      expose: true
      name: "Alfred"
      aliases:
        - "Vacuum"
        - "Vacuum Cleaner"
      room: "Living Room"
    switch.playstation_4:
      expose: true
      name: "PlayStation 4"
      aliases:
        - "PS4"
      room: "Living Room"
    switch.grissom:
      expose: true
      name: "Hackintosh"
      aliases:
        - "Hackintosh"
        - "Grissom"
      room: "Living Room"
    switch.zvox_power:
      expose: true
      name: "ZVOX"
      aliases:
        - "ZVOX"
        - "ZVOX Speaker"
        - "Soundbar"
      room: "Living Room"

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 1
  platform: jinvoo_smart

tplink:
  discovery: false
  switch:
    - host: 'iot-avocado'
    - host: 'iot-bacon'
    - host: 'iot-popcorn'

homeassistant: 
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
      allow_bypass_login: true
      trusted_users:
        192.168.1.0/24:
          - 568f9a82c34e4bbcb3275bc6ee3e3a60
  customize:
    # hide tuya switches since we are using them as lights
    switch.002008635ccf7f50842c:
      hidden: true
    switch.012002845ccf7f596568:
      hidden: true
    # Rename 
    sensor.network_throughput_in_eno1:
      friendly_name: "Ingress (eno1)"
    sensor.network_throughput_out_eno1:
      friendly_name: "Egress (eno1)"

light:
  - platform: switch
    name: "Desk Lamp"
    entity_id: switch.bacon
  - platform: switch
    name: "Corner Lamp"
    entity_id: switch.popcorn
  - platform: switch
    name: "TV Rack Lamp"
    entity_id: switch.avocado
  - platform: group
    name: Living Room
    entities:
      - light.corner_lamp
      - light.tv_rack_lamp

august:
  login_method: email
  username: !secret august_username
  password: !secret august_password

vacuum:
  - platform: xiaomi_miio
    host: 'iot-rockrobo'
    token: !secret roborock_token

switch:
  - platform: template
    switches:
      living_room_tv:
        friendly_name: 'Living Room TV'
        value_template: "{{ not is_state('binary_sensor.living_room_tv_status', 'off') }}"
        icon_template: "mdi:television"
        turn_on:
          service: switch.turn_on
          entity_id: switch.ir_living_room_tv
        turn_off:
          service: switch.turn_off
          entity_id: switch.ir_living_room_tv
      playstation_4:
        friendly_name: 'PlayStation 4'
        availability_template: "{{ not is_state('media_player.playstation_4', 'unknown') }}"
        value_template: "{{ not is_state('media_player.playstation_4', 'standby') }}"
        icon_template: "mdi:playstation"
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.playstation_4
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.playstation_4
      bedroom_tv:
        friendly_name: 'Bedroom TV'
        value_template: "{{ not is_state('media_player.bedroom_tv', 'off') }}"
        icon_template: "mdi:television"
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.bedroom_tv
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.bedroom_tv
      grissom:
        friendly_name: 'Grissom'
        value_template: "{{ not is_state('binary_sensor.grissom_status', 'off') }}"
        icon_template: "mdi:desktop-mac"
        turn_on:
          service: wake_on_lan.send_magic_packet
          data:
            mac: !secret grissom_mac
        turn_off:
          # TODO: find a way to sleep my hackintosh
          service: wake_on_lan.send_magic_packet
          data:
            mac: !secret grissom_mac
  - platform: broadlink
    type: rm2_pro_plus
    host: 'iot-rmpro'
    mac: !secret broadlink_mac
    switches:
      zvox_volume_up:
        friendly_name: "ZVOX Volume Up"
        command_off: "JgBIAAABKJQTExITEhMSFBEUEhMSExIUEjcSFBM2EhQSNxI4EjgSNxIUEjcSOBIUETgSFBEUEhMSOBITEhMSOBITEjgSOBI3EgANBQ=="
      zvox_volume_down:
        friendly_name: "ZVOX Volume Down"
        command_off: "JgBIAAABKJQTEhIUExISExIUExITEhMSEzcSExM3ExISOBQ2EzYTNxIUEjcUEhITExMSEhMTEhMTNxITEzcSNxM3FDYTNhM3EgANBQ===="
      zvox_mute:
        friendly_name: "ZVOX Mute"
        command_off: "JgBQAAABJpMSExISExISExMRFBESExMRFDYTEhM3EhITNxM2EjcUNhM3EhMSEhM3EzYSExMRFBETEhM3EjcTEhITEzYSNxQ2EwAFZgABJ0kSAA0FAAAAAAAAAAA="
      zvox_power:
        friendly_name: "ZVOX Power"
        command_on: "JgBQAAABKJMSEhISEhISEhISEhISEhISEjcSEhI3EhISNxI3EjcSNxI3EjcSEhI3EhISNxI3EjcSEhISEjcSEhI3EhISEhISEgAFZAABKEoSAAxWDQUAAAAAAAA="
        command_off: "JgBQAAABKJMSEhISEhISEhISEhISEhISEjcSEhI3EhISNxI3EjcSNxI3EjcSEhI3EjcSEhISEhISEhISEjcSEhISEjcSNxI3EgAFZAABKEoSAAxWDQUAAAAAAAA="
      ir_living_room_tv:
        friendly_name: "Living Room TV"
        command_on: 'JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU='
        command_off: 'JgBYAAABKpIVEBUQFjQVEBYQFRAVEBYPFjQVNRUQFjQVNRQ1FTUVNRUQFRAWEBU0FhAVEBUQFRAWNBU1FTQVERU0FTUWNBU1FQAFMgABK0cVAAxOAAErRxUADQU='


media_player:
  - platform: webostv
    host: 'living-room-tv'
    filename: webostv.conf
    timeout: 60
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret webostv_mac
    customize:
      sources:
        - Chromecast
        - Spotify
        - Netflix
        - Hulu
        - PlayStation 4
        - Nintendo Switch
        - YouTube
        - Optimum

sensor: !include_dir_merge_list sensors/

binary_sensor:
  - platform: ping
    name: living_room_tv_status
    host: 'living-room-tv'
    scan_interval: 1
    count: 1
  - platform: template
    sensors:
      grissom_status:
        value_template: "{{ (states('sensor.grissom_seconds_since_last_update') | int) < 60 }}"
  - platform: workday
    name: workday_today
    country: US
  - platform: workday
    name: workday_tomorrow
    country: US
    days_offset: 1

input_select:
  home_mode:
    name: "Home Mode"
    options:
      - "Home"
      - "Away"
      - "Party"
      - "Guests"
    initial: "Home"
    icon: mdi:home
  router_selected_interface:
    name: "Router Interface"
    options:
      - "WAN (eth1.2)"
      - "LAN (br-lan)"
      - "IoT (br-iot)"
    initial: "WAN (eth1.2)"
    icon: mdi:network-router
  router_selected_wifi:
    name: "Router Interface"
    options:
      - "The Promised LAN (5GHz)"
      - "The Promised LAN (2.4GHz)"
      - "IoT (2.4GHz)"
    initial: "The Promised LAN (5GHz)"
    icon: mdi:access-point-network

pi_hole:
  host: "nuc.thepromisedlan.club:443"
  location: pihole
  ssl: true

counter:
  num_vacuum_retries_today:
    initial: 0
    step: 1

spotcast:
  username: !secret spotify_username
  password: !secret spotify_password
