---
custom_header:
  compact_mode: true
resources:
  - type: js
    url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
  - type: js
    url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
  - type: module
    url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
  - type: js
    url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
  - type: module
    url: /hacsfiles/lovelace-state-switch/state-switch.js

title: Home
views: !include_dir_list lovelace/
