---
- platform: rest
  resource: https://nuc.thepromisedlan.club/vacuum/api/map/latest
  name: valetudo_map
  json_attributes:
    - image
    - path
    - charger
    - robot
  value_template: "OK"
  scan_interval: 60
