---
- alias: "Automatically set Home mode"
  trigger:
    - platform: state
      entity_id: binary_sensor.home_away
    - platform: state
      entity_id: person.luiz
    - platform: state
      entity_id: person.karin
  condition:
    condition: template
    value_template: "{{ not is_state('input_select.home_mode', 'Guests') }}"
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.home_mode
        option: >
          {%
            if is_state('binary_sensor.home_away', 'off') or
              is_state('person.luiz', 'home') or
              is_state('person.karin', 'home')
          %}
            Home
          {% else %}
            Away
          {% endif %}

- alias: "Disable Nest Home/Away when guests are staying"
  trigger:
    platform: state
    entity_id: binary_sensor.home_away
    to: "on"
  condition:
    condition: template
    value_template: "{{ is_state('input_select.home_mode', 'Guests') }}"
  action:
    - service: climate.set_preset_mode
      data_template:
        entity_id: climate.entryway
        preset_mode: "none"

- alias: "Force Nest to be Home when Home Mode is updated to Home"
  trigger:
    platform: state
    entity_id: input_select.home_mode
    to: "Home"
  action:
    - service: climate.set_preset_mode
      data_template:
        entity_id: climate.entryway
        preset_mode: "none"

- alias: "Home is now in Party Mode"
  trigger:
    platform: state
    entity_id: input_select.home_mode
    to: "Party"
  action:
    - service: automation.turn_off
      entity_id: automation.turn_off_living_room_lights

- alias: "Home is no longer in Party Mode"
  trigger:
    platform: state
    entity_id: input_select.home_mode
    from: "Party"
  action:
    - service: automation.turn_on
      entity_id: automation.turn_off_living_room_lights

- alias: "Automatically disable Party Mode"
  trigger:
    platform: state
    entity_id: input_select.home_mode
    to: "Party"
    for: "10:00:00"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.home_mode
        option: "Home"
