- alias: "Sync Home Mode with Nest"
  trigger:
    platform: state
    entity_id: binary_sensor.home_away
  condition:
    condition: template
    value_template: "{{ not is_state('input_select.home_mode', 'Guests') }}"
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.home_mode
        option: "{{ 'Home' if states('binary_sensor.home_away') == 'off' else 'Away' }}"

- alias: "Home is now in Party Mode"
  trigger:
    platform: state
    entity_id: input_select.home_mode
    to: "Party"
  action:
    - service: automation.turn_off
      entity_id: automation.turn_off_living_room_lights

- alias: "Home is no longer in Party Mode"
  trigger:
    platform: state
    entity_id: input_select.home_mode
    from: "Party"
  action:
    - service: automation.turn_on
      entity_id: automation.turn_off_living_room_lights

- alias: "Automatically disable Party Mode"
  trigger:
    platform: state
    entity_id: input_select.home_mode
    platform: state
    entity_id: device_tracker.paulus, device_tracker.anne_therese
    to: "Party"
    for: "10:00:00"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.home_mode
        option: "Home"
