---
- alias: "Turn on lights before sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  action:
    - service: light.turn_on
      entity_id: light.rack_lamps
    - service: light.turn_on
      entity_id: light.christmas_tree

- alias: "Turn off Christmas Tree"
  trigger:
    platform: time
    at: "01:00:00"
  action:
    - service: light.turn_off
      entity_id: light.christmas_tree

- alias: "Turn off Living Room lights"
  trigger:
    platform: time
    at: "22:30:00"
  condition:
    condition: state
    entity_id: binary_sensor.workday_tomorrow
    state: "on"
  action:
    - service: light.turn_off
      entity_id: light.rack_lamps
