---
- alias: Turn on ZVOX when TV turns on
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_tv_status
    to: "on"
  action:
    service: switch.turn_on
    entity_id: switch.zvox_power

- alias: Turn on ZVOX when PS4 turns on
  trigger:
    platform: state
    entity_id: switch.playstation_4
    to: "on"
  action:
    service: switch.turn_on
    entity_id: switch.zvox_power

- alias: Switch to Chromecast when PS4 turns off
  trigger:
    platform: state
    entity_id: switch.playstation_4
    to: "off"
  action:
    service: media_player.select_source
    data:
      entity_id: media_player.webos_living_room_tv
      source: Chromecast
