- alias: Turn on ZVOX when TV turns on
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_tv_status
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.zvox_power
