---
- alias: Turn on ZVOX when TV turns on
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_tv_status
    to: "on"
  action:
    service: switch.turn_on
    entity_id: switch.zvox_power

- alias: Turn on ZVOX when PS5 turns on
  trigger:
    platform: state
    entity_id: sensor.playstation_5
    to: "on"
  action:
    service: switch.turn_on
    entity_id: switch.zvox_power

- alias: Turn on ZVOX when Chromecast turns on
  trigger:
    platform: state
    entity_id: media_player.living_room_tv
    from: "off"
  action:
    service: switch.turn_on
    entity_id: switch.zvox_power

- alias: Switch to Chromecast when PS5 turns off
  trigger:
    platform: state
    entity_id: sensor.playstation_5
    to: "standby"
  action:
    service: media_player.select_source
    data:
      entity_id: media_player.webos_living_room_tv
      source: Chromecast

- alias: Turn off TV after being idle for 30 minutes
  trigger:
    platform: template
    value_template: >-
      {{
        is_state("switch.living_room_tv", "on")
        and is_state("media_player.living_room_tv", "off")
        and is_state_attr(
          "media_player.webos_living_room_tv",
          "source",
          "Chromecast"
        )
      }}
    for:
      minutes: 30
  action:
    service: switch.turn_off
    entity_id: switch.living_room_tv

- alias: Warn that TV will be turned off in 5 minutes
  trigger:
    platform: template
    value_template: >-
      {{
        is_state("switch.living_room_tv", "on")
        and is_state("media_player.living_room_tv", "off")
        and is_state_attr(
          "media_player.webos_living_room_tv",
          "source",
          "Chromecast"
        )
      }}
    for:
      minutes: 25
  action:
    service: notify.webos_living_room_tv
    data:
      message: "The TV will turn off in 5 minutes"
