---
- alias: Enable Flux on Home Assistant start
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.flux

- alias: Enable Flux every morning
  trigger:
    platform: time
    at: "05:00:00"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.flux

- alias: Update Flux when its state is set to on
  trigger:
    platform: state
    entity_id: switch.flux
    to: "on"
  action:
    - service: switch.flux_update
      data:
        entity_id: switch.flux
