---
- alias: Enable Flux on Home Assistant start
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.flux

- alias: Enable Flux every morning
  trigger:
    platform: time
    at: "05:00:00"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.flux

- alias: Update Flux when its state is set to on
  trigger:
    platform: state
    entity_id: switch.flux
    to: "on"
  action:
    - service: switch.flux_update
      data:
        entity_id: switch.flux

- alias: Update Flux every hour
  trigger:
    platform: time_pattern
    minutes: 0
  action:
    - service: switch.flux_update
      data:
        entity_id: switch.flux

- alias: "Open office blinds at sunrise"
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: cover.open_cover
      entity_id: cover.office_blinds

- alias: "Close office blinds at sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "+00:30:00"
  action:
    - service: cover.close_cover
      entity_id: cover.office_blinds
