---
- alias: "Start the Vacuum"
  trigger:
    platform: time
    at: "18:30:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_select.home_mode
        state: "Away"
  action:
    - service: vacuum.set_fan_speed
      data_template:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        # only run in max fan speed on Mondays
        fan_speed: "{{'Max' if now().weekday() == 0 else 'Balanced'}}"
    - service: vacuum.start
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner

- alias: "Retry on Vacuum errors"
  trigger:
    platform: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    to: error
    for: "00:00:30"
  condition:
    condition: numeric_state
    entity_id: counter.num_vacuum_retries_today
    below: 4
  action:
    - service: counter.increment
      data:
        entity_id: counter.num_vacuum_retries_today
    - service: vacuum.start
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner

- alias: "Reset Vacuum retry counter"
  trigger:
    platform: time
    at: "00:00:00"
  action:
    - service: counter.reset
      data:
        entity_id: counter.num_vacuum_retries_today

- alias: "Automatically dock the Vacuum"
  trigger:
    platform: time
    at: "19:00:00"
  action:
    - service: vacuum.return_to_base
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner

- alias: "Warn us when Vacuum is stuck"
  trigger:
    platform: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: counter.num_vacuum_retries_today
        above: 1
      - condition: template
        value_template: >-
          {{
            "move robot" in (
              state_attr("vacuum.xiaomi_vacuum_cleaner", "error") or ""
            )
          }}
  action:
    - service: notify.facebook
      data:
        message: "The vacuum seems to be stuck. Can you move it, please?"
        target: !secret phone_numbers
